### GENRE SEARCH TESTS


GET http://localhost:8080/search/genre?q="soft rock"&partial=true HTTP/2.0
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8080/search/genre?q=soft rock HTTP/2.0
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8080/search/genre?q=rock&partial=true HTTP/2.0
Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/search/genre?q=rock HTTP/2.0
Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/search/genre?q="RaP"&partial=true HTTP/2.0
Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/search/genre?q="rock" HTTP/2.0
Content-Type: application/json
Accept: application/json


### ARTIST SEARCH TESTS
GET http://localhost:8080/search/artist?q=daft punk HTTP/2.0
Content-Type: application/json
Accept: application/json


### TRACK SEARCH TESTS

GET http://localhost:8080/search/track?q=Contact HTTP/2.0
Content-Type: application/json
Accept: application/json


### ARTIST ID SEARCH TESTS
GET http://localhost:8080/search/artist/6WedqgL53vbco33SU3sVAX HTTP/2.0
Content-Type: application/json
Accept: application/json

