@SEARCH_URL = http://localhost:8080/search?
@PROTOCOL = HTTP/1.1

# MULTIPLE WORD GENRE SEARCH 
GET {{SEARCH_URL}}q=genre:"soft rock"&type=artist 
Content-Type: application/json

# SINGLE WORD WITH QUOTES GENRE SEARCH 
GET {{SEARCH_URL}}q="rock"&type=artist HTTP/1.1
Content-Type: application/json

# EXTRA WHITESPACE WITH QUOTES GENRE SEARCH 
GET {{SEARCH_URL}}q=genre:"  rock    "&type=artist HTTP/1.1
Content-Type: application/json

# EXTRA WHITESPACE WITH QUOTES MULTIPLE WORDS
GET {{SEARCH_URL}}q=genre:" soft rock    "&type=artist HTTP/1.1
Content-Type: application/json

# SINGLE WORD NO QUOTES
GET {{SEARCH_URL}}q=genre:rock&type=artist HTTP/1.1
Content-Type: application/json

# SINGLE WORD NO QUOTES EXTRA WHITESPACE
GET {{SEARCH_URL}}q=genre: rock   &type=artist HTTP/1.1
Content-Type: application/json

# MULTIPLE WORD NO QUOTES
GET {{SEARCH_URL}}q=genre:soft rock &type=artist HTTP/1.1
Content-Type: application/json

# MULTIPLE WORD NO QUOTES EXTRA WHITESPACE
GET {{SEARCH_URL}}q=genre:   soft  rock   &type=artist HTTP/1.1
Content-Type: application/json