### Test echo endpoint with valid request body
POST http://localhost:8080/echo HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "test": "this is some test data",
    "num": 24,
    "genres": ["test", "second", "elecro pop stuff"]
}

### Test echo with invalid method
GET http://localhost:8080/echo HTTP/1.1
Content-Type: application/json
Accept: application/json

{   

}

### Test echo enpoint with invalid input, should return an error response
POST http://localhost:8080/echo HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "test": 85,
    23232332: ''' 201-d 
}

### Test echo endpoint with invalid input that isn't json
POST http://localhost:8080/echo HTTP/1.1
Content-Type: application/json
Accept: application/json
